### ISSUE TITLE
Determine Appropriate License

### ISSUE THREAD

**Issue by jdhaines** [aiaa-deic/computation-ai#10]
The Computation AI repo has an Apache 2.0 license file, while the DevSecOps repo was created with an MIT license.  I'm not sure I have a real preference between the two and both seem like they might be appropriate.  We should decide and keep it the same for both though.  Any ideas @arthurrge?

**Comment by arthurrge** [comment]
I have no preference. Either is commercial-friendly - and I doubt we will have any "code" or IP per se. I agree let's keep it the same. I'm fine with either.
